name: CI

on:
  push:
    branches: [ '*' ]
    tags:
      - v*

jobs:
  linux_aarch64:
    name: Linux AARCH64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu
      - uses: actions/upload-artifact@v2
        with:
          name: aarch64
          path: target/**/release/races
          
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: aarch64
          
      - name: Display structure of downloaded files
        run: ls -R